trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: '20.x'
  GH_PAGES_REPO: 'itsmedigio/itsmedigio.github.io.git'
  SOURCE_DIR: 'out'

steps:

- checkout: self
  displayName: 'Checkout Source Repository 🛎'

- task: NodeTool@0
  displayName: 'Setup Node.js Environment 🏗'
  inputs:
    versionSpec: '$(NODE_VERSION)'

- task: Cache@2
  displayName: 'Cache npm packages'
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(Pipeline.Workspace)/.npm

- script: |
    npm config set cache $(Pipeline.Workspace)/.npm
    npm i --force
  displayName: 'Install dependencies 👨🏻‍💻'

- script: |
    npm run build
  displayName: 'Build Next.js Static Website 🚀'

- script: |
    set -e

    cd ..

    git clone https://$(ACCESS_TOKEN)@github.com/$(GH_PAGES_REPO) deploy_repo

    cd deploy_repo

    git rm -rf . || true

    cp -a ../$(Build.Repository.Name)/$(SOURCE_DIR)/. .

    ls -la

    git config user.email "itsmedigio@users.noreply.github.com"
    git config user.name "itsmedigio_cicd"

    git add . -A

    if git diff --cached --quiet; then
      echo "No changes detected."
      exit 0
    fi

    git commit -m "Automated deploy from Azure DevOps"
    git push

  displayName: 'Deploy to GitHub Pages 📤'
  env:
    ACCESS_TOKEN: $(ACCESS_TOKEN)