# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
    - run: npm ci
    - run: npm run build
    - run: |
        cd ..
        git clone https://${{secrets.ACCESS_TOKEN}}@github.com/itsmedigio/itsmedigio.github.io.git
        ls -la
        cp -a ./personalwebsite-azure-test/build/. ./itsmedigio.github.io.git/
        cd ./itsmedigio.github.io.git/
        ls -la
        git config --global credential.helper cache
        git config --local user.email "itsmedigio@users.noreply.github.com"
        git config --local user.name "itsmedigio"
        git add .
        git commit -m "Move build artifacts to deploy repo"
        git push
        
