# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: ls -la
    - run: pwd
    - name: Git Clone Action
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: itsmedigio/itsmedigio.github.io
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        platform: github # optional, default is github
        # Git branch or tag to checkout.
        ref: main # optional
        # Relative path from current directory, where to clone.
        path: secondrepo
    - run: cp -a ./build/. ./secondrepo/
    - run: ls -la ./secondrepo/
    - run: |
        cd ~/secondrepo
        git add .
        git commit -m "GitHub Actions Push from personalwebsite"
        git push
